controller_list:
  - name: fake_right_arm_controller
    joints:
      - torso_joint
      - right_shoulder_joint
      - right_s1_joint
      - right_s2_joint
      - right_s3_joint
  - name: fake_left_arm_controller
    joints:
      - torso_joint
      - left_shoulder_joint
      - left_s1_joint
      - left_s2_joint
      - left_s3_joint
  - name: fake_right_gripper_controller
    joints:
      []
  - name: fake_left_gripper_controller
    joints:
      - left_arm_gripper_joint